#!/usr/bin/env python3
import os
import subprocess
import serial.tools.list_ports

UBLOX_VID = 0x1546
ESP32_VID = 0x303a

def sanitize_port(port, baud):
    if not port or port == "virtual": return
    print(f"🛠️  Cleaning {port} for high-speed GPS...")
    # 1. Kill zombies holding the port open
    subprocess.run(["sudo", "fuser", "-k", port], stderr=subprocess.DEVNULL)
    # 2. Set kernel low_latency (The ASIO Fix)
    subprocess.run(["sudo", "setserial", port, "low_latency"], stderr=subprocess.DEVNULL)
    # 3. Force baud and raw mode (The Handshake Fix)
    subprocess.run(["sudo", "stty", "-F", port, str(baud), "raw", "-echo"], stderr=subprocess.DEVNULL)

def scan_and_export():
    ports = serial.tools.list_ports.comports()
    gps_device = next((p.device for p in ports if p.vid == UBLOX_VID), None)
    mcu_device = next((p.device for p in ports if p.vid == ESP32_VID), None)

    # Sanitize hardware BEFORE writing .env
    if gps_device: sanitize_port(gps_device, 460800)
    if mcu_device: sanitize_port(mcu_device, 460800)

    script_dir = os.path.dirname(os.path.abspath(__file__))
    env_path = os.path.join(script_dir, "docker", ".env")
    with open(env_path, "w") as f:
        f.write("# Auto-generated by fixusb.py with restored VID scanning\n")
        f.write(f"GPS_PORT={gps_device if gps_device else 'virtual'}\n")
        f.write(f"MCU_PORT={mcu_device if mcu_device else 'virtual'}\n")
        f.write(f"USER_ID={os.getuid()}\n")
        f.write(f"GROUP_ID={os.getgid()}\n")
    print(f"✨ .env updated. GPS: {gps_device}")

if __name__ == "__main__":
    scan_and_export()
