#!/usr/bin/env python3
import os
import serial.tools.list_ports

# Official Hardware IDs
UBLOX_VID = 0x1546  # u-blox AG
ESP32_VID = 0x303a  # Espressif Systems (ESP32-S3)

def scan_and_export():
    print("🔎 Scanning for Open Agbot Hardware...")
    ports = serial.tools.list_ports.comports()
    
    gps_device = None
    mcu_device = None

    for port in ports:
        if port.vid == UBLOX_VID:
            gps_device = port.device
            print(f"✅ Found u-blox GPS: {gps_device}")
        elif port.vid == ESP32_VID:
            mcu_device = port.device
            print(f"✅ Found ESP32 MCU:  {mcu_device}")

    # Determine the directory of the current script to place the .env file
    env_path = os.path.join(os.getcwd(), ".env")

    print(f"\n📝 Writing configuration to {env_path}...")
    
    try:
        with open(env_path, "w") as f:
            f.write("# Auto-generated by fixusb.py\n")
            f.write(f"GPS_PORT={gps_device if gps_device else '/dev/ttyACM0'}\n")
            f.write(f"MCU_PORT={mcu_device if mcu_device else '/dev/ttyACM1'}\n")
            # Adding UID/GID helps Docker avoid permission mismatches
            f.write(f"USER_ID={os.getuid()}\n")
            f.write(f"GROUP_ID={os.getgid()}\n")
        print("✨ .env file updated successfully.")
    except Exception as e:
        print(f"❌ Failed to write .env file: {e}")

    # Security check: Ensure the current user can actually read the ports
    if gps_device or mcu_device:
        print("\n🔐 Reminder: If you get 'Permission Denied', run:")
        if gps_device: print(f"   sudo chmod 666 {gps_device}")
        if mcu_device: print(f"   sudo chmod 666 {mcu_device}")

if __name__ == "__main__":
    scan_and_export()
